### ISSUE TITLE
Github CI/CD

### ISSUE THREAD

**Issue by 499689317** [499689317/notes#38]
### CI/CD脚本

* `mkdir .github/workflows`
* 创建.yaml文件
````
name: Deployment
on:
  push:
    branches: [ master]
#  workflow_dispatch:
#     inputs:
#       job:
#         description: 'feature branch'
#         required: true
#         default: 'feature-'
jobs:
  feature-deploy:
    runs-on: go-os
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with: github.event.inputs.job
      - name: Pull Config
        run: /bin/bash ./script/pull_config.sh dev
      - name: Build
        run: go build -o testCI ./main.go
      - name: Kill All
        run: /bin/bash ./script/kill.sh
      - name: Start All
        run: RUNNER_TRACKING_ID="" && nohup ./testCI test >> ./ci.log 2>&1 &      - name: Lookup
        run: ps -ef | grep testCI | grep -v grep
````

### 安装actions_runner

* 宿主机`mkdir actions_runner`
* 下载runner安装包
* 设置.Net环境
````
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
sudo yum install dotnet-sdk-6.0
````
* 解压并执行config.sh
* 设置对应的action标签
* 启动runner `./run.sh`
